# Generated by Django 4.2.19 on 2025-03-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('i', 'Intermediario'), ('A', 'Avancado'), ('B', 'Basico')], default='B', max_length=1),
        ),
    ]
